import json

# Full data set provided by user + NEW test case words
all_data = {
  "this": ["ito", "ire", "nito", "itong", "nitong"],
  "one": ["isang", "isa", "uno"],
  "not": ["hindi", "di", "dili"],
  "have": ["may", "mayroon", "meron", "magkaroon", "magkamit", "mayroong"],
  "study": ["aaral", "pag-aaral", "mag-aaral", "stadi", "study", "araling", "aralin", "studies"],
  "so that": ["upang", "para"],
  "as": ["bilang", "numero"],
  "if": ["kung", "kapag", "pag"],
  "their": ["kanilang", "kanila", "nila", "nilang"],
  "when": ["pag", "kapag", "tuwing", "kung"],
  "filipino": ["filipino", "pinoy", "pilipino", "pilipinong"],
  "for": ["para", "upang"],
  "https": ["https"],
  "do": ["mag", "gawin", "trabahuin", "buuin", "isagawa", "gawa"],
  "of this": ["nito", "niyan"],
  "other": ["iba", "kaiba", "ibang"],
  "from": ["mula", "galing", "buhat"],
  "only": ["lamang", "lang", "tanging", "isa", "bukod-tangi", "onli"],
  "because": ["dahil", "sapagkat", "kasi"],
  "more": ["mas", "higit", "lalo", "increasingly"],
  "journal": ["journal", "dyornal", "lathalain", "journals", "publikasyon"],
  "language": ["wika", "wikang", "lenggwahe", "language"],
  "philippines": ["pilipinas", "republika ng pilipinas", "philippines", "philippine"],
  "yet": ["pang", "para sa"],
  "teacher": ["guro", "titser", "tagapagturo", "maestro", "maestra", "teachers", "mga guro", "gurong", "propesor"],
  "research": ["pananaliksik", "saliksik", "riserts", "research"],
  "education": ["education", "edukasyon", "pagkatuto", "edukasyong", "edukeysyon"],
  "when (past)": ["nang", "na", "ng", "noong", "nung"],
  "com": ["com"],
  "www": ["www"],
  "can": ["maaaring", "pwede", "posibleng", "maaari"],
  "according to": ["ayon", "batay", "sang-ayon", "alinsunod", "sunod", "akording"],
  "country": ["bansa", "nasyon", "kantri", "bayan", "bansang", "republika"],
  "through": ["pamamagitan", "gamit", "paraan", "through"],
  "teaching": ["pagtuturo", "titsing", "teaching", "nagtuturo", "gumagabay", "nagleksyon"],
  "became": ["naging"],
  "usage": ["paggamit", "gamit", "yuseyds"],
  "become": ["maging", "magiging", "nagiging"],
  "org": ["org"],
  "person": ["tao", "indibidwal", "person"],
  "university": ["university", "unibersidad", "pamantasan", "pamantasang", "yunibersiti"],
  "learning": ["pagkatuto", "learning", "kaalaman"],
  "his": ["kaniyang", "kanyang", "niya", "kaniya"],
  "analysis": ["pagsusuri", "analisis", "pag-aanalisa", "analysis"],
  "so": ["kaya", "dahil dito", "gayon", "ganun"],
  "here": ["dito", "rito", "dine"],
  "researcher": ["mananaliksik", "risertser", "tagapagsaliksik", "researchers", "siyentipiko"],
  "in": ["nasa", "sa"],
  "experience": ["karanasan", "ekspiryensya", "pinagdaanan", "karanasang", "natutunan", "ekspiryens"],
  "part": ["bahagi", "parte", "kapiraso", "part", "bahaging", "seksyon", "piraso", "pangkat"],
  "period": ["panahon", "tyempo", "oras", "period"],
  "they": ["sila", "kaniya", "silang"],
  "to": ["kay", "kila", "kina"],
  "all": ["lahat", "pangkalahatan"],
  "based": ["batay", "base", "ayon", "based", "nakabase", "hango", "beysd", "nakabatay", "nakasalalay", "naka-base"],
  "development": ["development", "pag-unlad", "debelopment", "pag-asenso", "pagsulong", "paglago"],
  "without": ["walang", "wala"],
  "like": ["tulad", "gaya", "kapareho", "katulad"],
  "culture": ["kultura", "culture", "kinagawian", "kulturang"],
  "level": ["antas", "lebel", "level"],
  "student": ["mag-aaral", "estudyante", "student", "students", "iskolar"],
  "doi": ["doi"],
  "knowledge": ["kaalaman", "knowledge", "karunungan", "dunong", "talino", "nolidj"],
  "data": ["datos", "data", "impormasyon", "tala", "deyta"],
  "method": ["paraan", "metodo", "method", "pamamaraan", "metodo", "sistema", "metod"],
  "word": ["salita", "word", "kataga", "salitang"],
  "where": ["san", "saan"],
  "online": ["online", "onlayn", "internet"],
  "but": ["ngunit", "subalit", "datapwat", "pero", "kundi", "kundi man"],
  "using": ["gamit", "paggamit", "yus", "using", "sa", "pamamagitan", "yusing", "gumagamit", "nagamit", "nagsasagawa", "kumokonsumo", "yuser"],
  "each": ["bawat", "kada"],
  "social": ["social", "sosyal", "panlipunan", "panlipunang", "pambayan"],
  "manila": ["manila", "maynila"],
  "own": ["sariling", "sarili"],
  "he": ["siya", "kaniya", "siyang"],
  "participant": ["kalahok", "participant", "respondente", "sumagot", "kasali", "respondent"],
  "must": ["dapat", "kailangan"],
  "international": ["international", "internasyonal", "pandaigdigan"],
  "about": ["tungkol", "ukol", "hinggil"],
  "some": ["ilang", "ilan", "iilang"],
  "lot": ["lot"],
  "until": ["hanggang", "asta"],
  "edu": ["edu"],
  "volume": ["volume", "bolyum", "vol", "tomo"],
  "skill": ["kasanayan", "skill", "iskil", "kakayahan", "kakayahang", "galing", "abilidad", "competencies", "kasanayang", "skills", "talento"],
  "ateneo": ["ateneo"],
  "history": ["kasaysayan", "historya", "nakaraan", "history", "makasaysayan"],
  "writing": ["pagsulat", "pagsusulat", "writing", "sulatin", "akda", "artikulo", "sanaysay", "papel", "sulat", "rayting"],
  "inside": ["loob", "ilalim"],
  "first": ["unang", "una", "pang-una", "first", "pirst", "muna", "bago", "saglit"],
  "katipunan": ["katipunan"],
  "like this": ["ganitong", "ganito", "ganyan"],
  "being": ["pagiging"],
  "objective": ["layunin", "mithiin", "tunguhin", "objective"],
  "my": ["aking", "akin", "kong", "ko"],
  "index": ["index", "indeks"],
  "primary": ["pangunahing", "pangunahi", "main", "basic", "basiko"],
  "life": ["buhay", "pamumuhay", "life", "layp", "kapalaran"],
  "city": ["city", "lungsod", "siyudad"],
  "effect": ["epekto", "impluwensya", "bunga", "effect", "bisa", "lakas", "pwersa", "epektibnes", "impact", "impak", "implikasyon"],
  "community": ["komunidad", "pamayanan", "community"],
  "paper": ["papel", "dokumento", "paper", "pahina", "peyper"],
  "task": ["gawain", "aktibidad", "task", "trabaho", "gawaing"],
  "two": ["dalawang", "dalawa", "dos", "tu", "pares", "pareho"],
  "perspective": ["pananaw", "paningin", "perspektiba", "perspective"],
  "our": ["ating", "atin", "natin", "awer", "nating", "tayo"],
  "society": ["lipunan", "sosyedad", "society", "lipunang", "bayan", "komunidad"],
  "what": ["ano", "anong", "alin", "bakit", "wat"],
  "meaning": ["kahulugan", "ibig sabihin", "meaning", "nangangahulugang", "sumisimbolo", "tumutukoy", "mining"],
  "use": ["ginamit", "ginagamit", "gamit", "paggamit", "gumamit", "gamitin", "yus"],
  "visible": ["makikita", "nakikita", "matatagpuan"],
  "science": ["science", "agham", "siyensya", "sciences"],
  "table": ["talahanayan", "teybol", "table", "lamesa", "hapag"],
  "change": ["pagbabago", "transpormasyon", "change", "pagbabagong", "pag-iiba", "paglipat", "pagsasaayos", "tseng"],
  "place": ["lugar", "pook", "lokasyon", "place"],
  "how": ["paano", "pano"],
  "school": ["school", "paaralan", "eskwelahan", "iskul", "aralan", "klase"],
  "example": ["halimbawa", "ehemplo", "example"],
  "los": ["los"],
  "issue": ["issue", "isyu", "usapin", "problema", "isyung"],
  "of": ["nina"],
  "national": ["national", "pambansa", "nasyonal", "pambansang", "pambayan", "panlahat"],
  "essay": ["sanaysay", "artikulo", "essay"],
  "creation": ["pagbuo", "paggawa", "pormasyon", "paglikha", "pag-imbento", "pag-create"],
  "review": ["review", "rebyu", "pagsusuri"],
  "type": ["uri", "klase", "tipo", "type"],
  "reyes": ["reyes"],
  "new": ["bagong", "bago", "nyu", "new"],
  "art": ["sining", "arte", "art", "arts", "obra"],
  "many": ["maraming", "marami", "madami"],
  "included": ["kabilang", "kasama", "nakapaloob", "nasa", "laman"],
  "important": ["mahalagang", "mahalaga", "importante", "makabuluhan", "mahahalagang", "seryoso", "signipikant"],
  "connection": ["ugnayan", "kaugnay", "koneksyon", "relasyon"],
  "concept": ["konsepto", "ideya", "concept", "dalumat", "konseptong", "teorya", "pananaw"],
  "related": ["kaugnay", "konektado", "relasyon"],
  "result": ["resulta", "kinalabasan", "bunga", "result"],
  "while": ["habang", "samantala"],
  "high": ["mataas", "matayog", "high"],
  "inc": ["inc"],
  "self": ["sarili", "pansarili"],
  "current": ["kasalukuyang", "kasalukuyan", "ngayon"],
  "process": ["proseso", "hakbang", "daloy", "process"],
  "curriculum": ["curriculum", "kurikulum", "programa", "pangkurikulum", "pang-aralin", "pampaaralan", "pang-akademya", "kurikular"],
  "corner": ["corner", "kanto", "sulok"],
  "also": ["ring", "din", "rin", "ding", "pati", "saka", "also"],
  "even": ["man", "kahit", "bagaman", "maski"],
  "personal": ["personal", "pansarili", "pribado"],
  "year": ["taong", "taon", "year"],
  "ritual": ["ritwal", "gawi", "tradisyon", "ritual", "bogwa"],
  "context": ["konteksto", "sitwasyon", "context"],
  "value": ["pagpapahalaga", "halaga", "value", "importansya"],
  "php": ["php"],
  "thing": ["bagay", "gamit", "object"],
  "time": ["oras", "panahon", "time", "panahong", "petsa", "dekada", "tyempo"],
  "said": ["nasabing", "sinabing", "sed", "winika", "binanggit", "inihayag", "naturang", "nabanggit"],
  "indeed": ["nga"],
  "http": ["http"],
  "reading": ["pagbasa", "pagbabasa", "reading", "rinding", "pag-unawa"],
  "none": ["wala", "walang"],
  "college": ["kolehiyo", "pamantasan", "college"],
  "retrieved": ["kinuha", "nakuha", "retrieved"],
  "that": ["yung", "iyung", "yaong", "iyon", "yun"],
  "guide": ["gabay", "patnubay", "gayd"],
  "towards": ["tungo", "papunta", "patungo", "diretso", "tword"],
  "challenge": ["hamon", "pagsubok", "tsalends", "tsalenges"],
  "multidisciplinary": ["multidisiplinaryo", "multidisciplinary"],
  "importance": ["kahalagahan", "importansya", "halaga"],
  "university": ["unibersidad", "pamantasan", "university"],
  "digital": ["digital", "dihital"],
  "continuous": ["patuloy", "tuloy-tuloy", "tuloy"],
  "quezon": ["quezon"],
  "particular": ["partikular", "tiyak", "partikularmente"],
  "standard": ["pamantayan", "batayan", "standard", "pamantayang", "sukatan", "panuntunan", "istandard"],
  "topic": ["paksa", "tema", "topik"],
  "reason": ["dahilan", "rason", "sanhi"],
  "salle": ["salle", "la salle"],
  "day": ["araw", "petsa"],
  "mean": ["mean", "average", "gitna"],
  "awareness": ["malay", "kamalayan", "awernes"],
  "having": ["pagkakaroon", "pag-iral", "presensya", "nagkakaroon", "nakakakuha", "nagiging", "lumilitaw", "habing"],
  "translation": ["pagsasalin", "pag-translate", "transleysyon", "salin", "translation"],
  "work": ["trabaho", "hanapbuhay", "work", "gawa", "likha", "produkto", "werk"],
  "content": ["content", "nilalaman", "laman", "pangnilalaman", "sustansya", "kahulugan", "buod", "kontent"],
  "big": ["malaking", "malaki", "dambuhala", "big"],
  "belief": ["paniniwala", "pananampalataya", "bilip", "bilips"],
  "media": ["media", "midya", "peysbuk"],
  "need": ["pangangailangan", "kailangan", "kailangang", "nid", "dapat", "humihingi", "umaasa", "nidi"],
  "nature": ["kalikasan", "kaligiran", "neytsur"],
  "program": ["programa", "palatuntunan", "program", "programang"],
  "understanding": ["unawa", "pag-unawa", "intindi"],
  "field": ["larangan", "field", "aspeto"],
  "information": ["impormasyon", "datos", "information", "detalye"],
  "gives": ["nagbibigay", "naglalaan", "bigay"],
  "problem": ["suliranin", "problema", "isyu", "suliraning", "hamon", "pagsubok", "balakid"],
  "clear": ["malinaw", "klaro", "klir"],
  "grade": ["grade", "marka", "greyd", "baitang", "grado", "markahan", "kwarter", "iskoran"],
  "besides": ["bukod", "maliban"],
  "issn": ["issn"],
  "local": ["lokal", "pampook", "lokasyon"],
  "meeting": ["salubong", "pagsalubong"],
  "english": ["ingles", "english"],
  "press": ["press", "palimbagan", "pres"],
  "lesson": ["aralin", "leksyon", "aral", "kaalaman", "leson"],
  "whole": ["buong", "buo", "kabuuan"],
  "characteristic": ["katangian", "deskripsyon"],
  "three": ["tatlong", "tatlo", "tres"],
  "rizal": ["rizal"],
  "lack": ["kakulangan", "kulang", "kakapusan"],
  "world": ["mundo", "daigdig", "earth", "world", "werld"],
  "mentioned": ["nabanggit", "nasabi", "tinukoy", "binanggit"],
  "academic": ["akademikong", "akademiko", "academic"],
  "condition": ["kalagayan", "sitwasyon", "kondisyon"],
  "statement": ["pahayag", "sinabi", "deklarasyon"],
  "completely": ["lubos", "masyado", "sobra"],
  "airport": ["paliparan", "erport"],
  "orderly": ["maayos", "organisado", "ayos"],
  "deep": ["malalim", "matindi", "dip"],
  "text": ["teksto", "text", "artikulo"],
  "between": ["pagitan", "gitna", "between", "sa", "bitwin"],
  "now": ["ngayon", "kasalukuyan"],
  "making": ["paggawa", "pagbuo", "gawa"],
  "likewise": ["gayundin", "pati", "saka"],
  "form": ["anyo", "porma", "hugis"],
  "image": ["imahen", "imahe", "larawan", "imeyds"],
  "asia": ["asya", "asia", "kontinente", "esya", "asyano", "oriental", "taga-asya", "asyan"],
  "equipment": ["kagamitan", "gamit", "instrumento", "kagamitang"],
  "village": ["barangay", "baranggay", "komunidad"],
  "vicente": ["vicente"],
  "giving": ["pagbibigay", "pag-aabot", "bigay"],
  "lots": ["lots"],
  "enough": ["sapat", "husto", "inaf"],
  "his/her": ["niyang", "niya", "kaniya", "kanya", "sarili"],
  "residential": ["residential", "residensyal", "panirahan"],
  "citizen": ["mamamayan", "taumbayan", "sitisen"],
  "god": ["diyos", "panginoon", "god", "hesus", "kristo", "shaddai"],
  "project": ["proyekto", "plano", "project"],
  "theme": ["tema", "paksa", "theme"],
  "communication": ["komunikasyon", "pakikipag-ugnayan", "communication", "ugnayan", "usapan", "pakikipagtalastasan"],
  "family": ["pamilya", "mag-anak", "family"],
  "book": ["aklat", "libro", "book", "babasahin", "buk"],
  "showing": ["nagpapakita", "nagpapamalas", "pakita", "ipinapakita", "nilalahad", "ibinubunyag", "pinapahiwatig", "dinidispley"],
  "want": ["nais", "gusto", "ibig", "mahal", "pagnanasa"],
  "mixed": ["mixed", "halo", "magkahalo"],
  "cultural": ["cultural", "kultural", "pangkalinangan"],
  "saleable": ["saleable", "mabenta"],
  "literary work": ["akda", "likha", "panitikan", "akdang"],
  "management": ["pamamahala", "pangangasiwa", "management"],
  "article": ["article", "artikulo", "lathalain"],
  "question": ["tanong", "katanungan", "question"],
  "subject": ["asignaturang", "asignatura", "sabjek", "subjects", "aralin", "kurso", "paksa"],
  "program": ["program", "programang", "programa", "palatuntunan"],
  "addition": ["dagdag", "karagdagan", "adisyon"],
  "connection": ["ugnayan", "kaugnay", "koneksyon", "relasyon"],
  "response": ["tugon", "sagot", "response", "pagtugon", "pagsagot", "aksyon", "pagharap", "respons"],
  "pdf": ["pdf"],
  "tagalog": ["tagalog"],
  "system": ["sistema", "sistem", "system"],
  "technology": ["teknolohiya", "tek", "technology", "makinarya"],
  "wide": ["malawak", "malapad", "saklaw"],
  "gov": ["gov"],
  "child": ["bata", "paslit", "tsayld", "anak", "supling", "children"],
  "chosen": ["piling", "pinili", "hirang"],
  "literature": ["panitikan", "literatura", "literature", "literatyur"],
  "finish": ["matapos", "tapusin", "tapos"],
  "body": ["katawan", "pisikal", "body"],
  "interview": ["panayam", "interbyu", "interview", "pakikipanayam", "usapan"],
  "class": ["klase", "uri", "class", "pangkat", "aralin", "klas"],
  "ijfmr": ["ijfmr"],
  "native": ["katutubong", "katutubo", "neytib"],
  "land": ["lupa", "lupain", "land"],
  "help": ["tulong", "suporta", "asiste", "helping"],
  "step": ["hakbang", "proseso", "step"],
  "ojs": ["ojs"],
  "art": ["art", "arts", "sining", "arte"],
  "again": ["muling", "muli", "ulit", "bago", "saka", "a-gen"],
  "space": ["espasyo", "puwang", "space"],
  "other side": ["kabila", "ibayo"],
  "discipline": ["disiplina", "asal", "discipline"],
  "under": ["ilalim", "baba", "under", "sakop", "ander"],
  "government": ["pamahalaan", "gobyerno", "government", "liderato"],
  "idea": ["ideya", "kaisipan", "idea"],
  "house": ["bahay", "tahanan", "house"],
  "carabao": ["kalabaw", "carabao"],
  "state": ["state", "estado", "kalagayan", "sitwasyon", "bansa", "istatus"],
  "water": ["tubig", "water"],
  "worker": ["manggagawa", "empleyado", "trabahador"],
  "after": ["pagkatapos", "tapos", "after"],
  "environment": ["kapaligiran", "kalikasan", "environment"],
  "basis": ["batayan", "basehan", "pamantayan"],
  "why": ["bakit", "why"],
  "journey": ["paglalakbay", "biyahe", "travel"],
  "execution": ["pagsasagawa", "paggawa", "implementasyon"],
  "factor": ["salik", "dahilan", "factor", "elemento", "bahagi", "paktor"],
  "four": ["apat", "kwatro", "four"],
  "normal": ["normal", "karaniwan"],
  "deped": ["deped"],
  "region": ["rehiyon", "probinsya", "region"],
  "linguistic": ["pangwika", "wika", "linggwistiko", "linguistics", "linggwistiks"],
  "meanwhile": ["samantala", "habang", "samantalang", "ngunit", "subalit", "minwayl", "namang", "rin", "naman"],
  "true": ["tunay", "totoo", "true"],
  "lapulapu": ["lapulapu"],
  "focused": ["nakatuon", "nakapokus", "pokus"],
  "basic": ["basic", "basiko", "pangunahin"],
  "december": ["disyembre", "december", "buwan", "petsa", "disyember"],
  "recognition": ["pagkilala", "rekognisyon"],
  "diliman": ["diliman"],
  "identity": ["identidad", "pagkakakilanlan"],
  "conducted": ["isinagawa", "ginawa", "isinagawang", "tinapos", "nilikha", "kondukted"],
  "performance": ["pagganap", "perpormans", "performance", "pagtatanghal", "palabas", "dula", "perpo"],
  "disease": ["sakit", "karamdaman", "virus", "disis"],
  "we": ["tayo", "kami"],
  "health": ["health", "kalusugan", "katawan", "sigla", "lakas", "helt"],
  "pasma": ["pasma"],
  "second": ["ikalawang", "pangalawa", "ikalawa", "dos", "sumunod", "sekond"],
  "quality": ["kalidad", "uri", "quality"],
  "pandemic": ["pandemya", "pandemic", "kobid"],
  "lifestyle": ["pamumuhay", "buhay"],
  "who": ["who", "sino"],
  "had": ["nagkaroon", "nagka"],
  "technical": ["teknikal", "technical"],
  "training": ["pagsasanay", "treyning"],
  "letter": ["titik", "letra"],
  "tradition": ["tradisyon", "kinagawian"],
  "news": ["news", "balita"],
  "any": ["anumang", "kahit ano"],
  "publishing": ["publishing", "paglalathala"],
  "dlsu": ["dlsu", "de la salle"],
  "then": ["noon", "dati"],
  "emphasis": ["diin", "empasis"],
  "positive": ["positibong", "positibo"],
  "mathematics": ["mathematics", "matematika", "sipnayan", "mat", "matematiks"],
  "published": ["published", "inilathala"],
  "way": ["daan", "paraan", "kalsada"],
  "individual": ["indibidwal", "tao", "individual"],
  "music": ["musika", "music"],
  "juan": ["juan"],
  "cause": ["dulot", "sanhi", "dahilan", "rason", "puno", "pinagmulan"],
  "impact": ["impact", "epekto", "impak", "implikasyon"],
  "native": ["katutubo", "neytib", "katutubong"],
  "theory": ["theory", "teorya", "palagay", "hinuha", "prinsipyo"],
  "original": ["orihinal", "original"],
  "accepted": ["tinanggap", "inako"],
  "educational": ["educational", "pang-edukasyon"],
  "church": ["simbahan", "iglesya"],
  "fellow": ["kapwa", "kapareho"],
  "south": ["timog", "south"],
  "magellan": ["magellan"],
  "design": ["disenyo", "design"],
  "often": ["madalas", "palagi"],
  "number": ["blg", "bilang"],
  "june": ["june", "hunyo"],
  "event": ["pangyayari", "insidente"],
  "law": ["batas", "law"],
  "th": ["ika-", "pang-"],
  "lake": ["lawa", "lake"],
  "common": ["karaniwang", "karaniwan", "normal"],
  "palawan": ["palawan"],
  "ancient": ["sinaunang", "luma", "ancient"],
  "message": ["mensahe", "message"],
  "filipinology": ["filipinolohiya", "pag-aaral ng pilipinas"],
  "wvsu": ["wvsu"],
  "jstor": ["jstor"],
  "picture": ["larawan", "imahe"],
  "possible": ["posibleng", "maaari"],
  "appropriate": ["angkop", "bagay", "nararapat", "tama", "wasto"],
  "refers": ["tumutukoy", "nagpapahiwatig", "nangangahulugan", "nagsasabi", "naglalarawan"],
  "interest": ["interes", "hilig", "gusto", "nais", "pagnanasa"],
  "stable": ["stable", "matatag", "pirmihan", "panatag", "matibay"],
  "significant": ["significant", "mahalaga", "makabuluhan", "importante", "signipikant", "matinding"],
  "materials": ["materials", "materyales", "kagamitan", "sangkap", "materyals"],
  "group": ["group", "grupo", "pangkat", "samahan", "grup", "pulutong", "sirkulo"],
  "awareness": ["kamalayan", "malay", "unawa", "pagkaalam", "awernes"],
  "specific": ["tiyak", "sigurado", "tumpak", "klaro", "ispesipiko"],
  "thought": ["kaisipan", "ideya", "pananaw", "isip", "konsepto"],
  "framework": ["balangkas", "istruktura", "plano", "banghay", "pormat"],
  "values": ["pagpapahalagang", "importansya", "paggalang", "pag-ibig", "balyu"],
  "woman": ["babae", "ginang", "binibini", "dalaga", "kababaihan", "wimen"],
  "really": ["talaga", "tunay", "totoo", "sigurado", "seryoso"],
  "communication": ["communication", "komunikasyon", "ugnayan", "usapan", "pakikipagtalastasan"],
  "model": ["modelo", "huwaran", "ehemplo", "tularan", "model"],
  "respondent": ["respondente", "sumagot", "kalahok", "kasali", "respondent"],
  "unfolding": ["pagtitiklad", "pagbubukas", "paglalatag", "pagpapakita", "pag-usisa"],
  "ability": ["kakayahang", "galing", "talento", "abilidad", "kapasidad"],
  "both": ["parehong", "kapwa", "pantay", "katulad", "pareho"],
  "graduated": ["nagsipagtapos", "nagtapos", "naggradweyt", "nakatapos", "nakapasa"],
  "economy": ["ekonomiya", "kabuhayan", "pananalapi", "kalakalan", "ekonomiks"],
  "reference": ["sanggunian", "reperensya", "batayan", "pinagkunan", "sors"],
  "discourse": ["diskurso", "talakayan", "usapan", "pag-uusap", "debate"],
  "complete": ["ganap", "buo", "lubos", "kumpleto", "perpekto"],
  "exactly": ["mismo", "sadya", "eksakto", "tumpak", "mismong"],
  "serving": ["nagsisilbing", "gumaganap", "nagiging", "tumatayong", "umaakto"],
  "understand": ["maunawaan", "maintindihan", "malaman", "matutunan", "magets"],
  "correct": ["wastong", "tama", "tumpak", "angkop", "nararapat"],
  "open": ["open", "bukas", "lantad", "malaya", "openg"],
  "although": ["bagaman", "kahit", "subalit", "gayunman", "pero", "bagamat"],
  "page": ["pahina", "dahon", "bahagi", "mukha", "peyj"],
  "discovered": ["natuklasan", "nalaman", "nahanap", "nadiskubre", "nakita"],
  "modern": ["makabagong", "bago", "moderno", "sariwa", "napapanahon"],
  "mother": ["mother", "ina", "nanay", "inay", "mama"],
  "sound": ["tunog", "ingay", "himig", "boses", "sawnd"],
  "song": ["awitin", "kanta", "himig", "musika", "song", "awiting"],
  "say": ["sabihin", "banggitin", "ibigkas", "ipahayag", "wika"],
  "majority": ["karamihan", "kadalasan", "marami", "nakararami", "mayorya"],
  "attention": ["pansin", "atensyon", "puna", "pag-aalaga", "tingin"],
  "bicol": ["bikol", "bikolano", "rehiyon", "lengguwahe"],
  "saint": ["santo", "banal", "poon", "sagrado", "seynt", "santos"],
  "required": ["kinakailangan", "kailangan", "nararapat", "dapat", "rekwayrment"],
  "meaningful": ["makabuluhang", "mahalaga", "makatuturan", "importante", "signipikant"],
  "department": ["department", "kagawaran", "sangay", "opisina", "departamento"],
  "progress": ["unlad", "asenso", "sulong", "progreso", "pag-angat"],
  "interpretation": ["interpretasyon", "paliwanag", "pagpapakahulugan", "pag-unawa", "pagsasalin", "pagtingin", "mining"],
  "part": ["bahaging", "parte", "seksyon", "piraso", "pangkat"],
  "fruit": ["bunga", "resulta", "epekto", "kinabukasan", "prutas"],
  "parents": ["magulang", "nanay", "tatay", "tagapag-alaga", "pareyts"],
  "almost": ["halos", "malapit", "tila", "medyo", "parang"],
  "right": ["tamang", "wasto", "tumpak", "angkop", "nararapat"],
  "physical": ["pisikal", "katawan", "panlabas", "materyal"],
  "stage": ["yugto", "bahagi", "kabanata", "panahon", "lebel"],
  "philosophy": ["pilosopiya", "kaisipan", "pananaw", "paniniwala"],
  "ghoul": ["aswang", "halimaw", "bampira", "maligno"],
  "opportunity": ["pagkakataon", "tsansa", "panahon", "opurtunidad", "tyempo"],
  "print": ["print", "limbag", "kopya", "imprenta"],
  "mine": ["akin", "ko", "sarili", "pag-aari", "mayn"],
  "improving": ["pagpapaunlad", "pagpapabuti", "pagpapalago", "pagpapaganda", "debelopment"],
  "reading": ["reading", "pagbasa", "pagbabasa", "pag-unawa", "rinding"],
  "cross": ["cruz", "krus", "apelyido", "krusipikso"],
  "resurrection": ["pagkabuhay", "muling-pagbangon", "pag-asa", "paggising", "resureksyon"],
  "power": ["kapangyarihan", "lakas", "pwersa", "awtoridad", "paway"],
  "sustainable": ["sustainable", "napapanatili", "matatag", "nagpapatuloy", "sasteynabol"],
  "youtube": ["youtube", "bidyo", "panoorin", "platform", "yutub"],
  "did": ["nag", "nag-umpisa", "gumawa", "naging"],
  "active": ["aktibong", "masigla", "gumagalaw", "mabilis", "aktib"],
  "animal": ["hayop", "nilalang", "alaga", "halimaw", "animal"],
  "such": ["gayong", "ganoon", "tulad", "kahit", "ganito"],
  "former": ["dating", "nakaraan", "luma", "dati", "pormer"],
  "easy": ["madaling", "mabilis", "simple", "payak", "i-si"],
  "sake": ["alang", "dahil", "para", "alang-alang", "rason"],
  "hall": ["bulwagang", "kwarto", "pasilyo", "tanggapan", "hall"],
  "tracer": ["tracer", "tagasubaybay", "hanapin", "pagsusuri", "treyser"],
  "know": ["alam", "batid", "kilala", "naiintindihan", "nadiskubre"],
  "writing": ["sulatin", "akda", "artikulo", "sanaysay", "papel"],
  "will use": ["gagamitin", "uubusin", "isasagawa", "ipapatupad", "yuz"],
  "material": ["materyal", "gamit", "bagay", "pisikal", "materyales"],
  "acceptance": ["pagtanggap", "pagkuha", "pag-ako", "pag-ayon", "akseptans"],
  "outside": ["labas", "luwas", "panlabas", "awtsayd", "isyu"],
  "theory": ["teorya", "palagay", "hinuha", "prinsipyo"],
  "your": ["iyong", "mo", "inyo", "sarili", "yor"],
  "organization": ["organisasyon", "samahan", "grupo", "kapisanan"],
  "general": ["pangkalahatang", "buo", "panlahat", "karaniwan", "dyeneral", "general", "heneral"],
  "code": ["code", "kodigo", "batas", "panuntunan", "kowd"],
  "province": ["lalawigan", "probinsya", "rehiyon", "bayan", "probins"],
  "against": ["laban", "kontra", "salungat", "tunggalian", "paligsahan"],
  "consisting": ["binubuo", "nilalaman", "sakop", "gawa", "ginagawa"],
  "narrative": ["naratibo", "kwento", "salaysay", "paglalahad", "naratib"],
  "arts": ["artes", "sining", "kakayahan", "obra", "arts"],
  "aspect": ["aspekto", "bahagi", "anggulo", "panig", "aspeto", "aspektong", "mukha"],
  "senior": ["senior", "nakatatanda", "matanda", "pinuno", "sinyor"],
  "core": ["core", "gitna", "sentro", "puso", "kor"],
  "synchronous": ["synchronous", "sabay", "magkasabay", "kasalukuyan", "sinkronus"],
  "century": ["siglo", "dantaon", "daantaon", "senturyo", "sentyuri"],
  "called": ["tinatawag", "binabanggit", "kinikilala", "pinapangalanan", "tawag"],
  "solution": ["solusyon", "lunas", "sagot", "kalutasan"],
  "seems": ["tila", "parang", "mukhang", "wari", "yata", "animo"],
  "last": ["huling", "dulo", "pinal", "wakas", "last"],
  "structure": ["estruktura", "balangkas", "gusali", "porma", "istruktura"],
  "jose": ["jose", "pangalan", "pepe", "hose"],
  "master": ["master", "guro", "amo", "dalubhasa"],
  "scholar": ["iskolar", "mag-aaral", "matalino", "estudyante"],
  "frequency": ["frequency", "dalas", "bilang", "paulit-ulit", "prikwensi"],
  "situation": ["sitwasyon", "kalagayan", "estado", "pangyayari"],
  "polytechnic": ["politeknikong", "teknikal", "unibersidad", "paaralan", "politeknik"],
  "analyzed": ["nasusuri", "na-oobserbahan", "natitingnan", "natitimbang", "naaanalisa", "sinuri", "tinignan", "binusisi", "inaral", "tsinek"],
  "support": ["suporta", "tulong", "saklolo", "alalay", "suport"],
  "order": ["order", "utos", "ayos", "bili"],
  "environmental": ["environmental", "pangkalikasan", "kapaligiran", "natural", "enbayronmental"],
  "strategy": ["estratehiya", "pamamaraan", "plano", "taktika", "istratedyi"],
  "hero": ["bayani", "idolo", "bida", "magiting", "hiro"],
  "considered": ["itinuturing", "kinikilala", "pinalalagay", "tinitingnan", "konsider", "maituturing", "masasabi", "makikilala", "maipapalagay"],
  "saw": ["nakita", "nahanap", "natagpuan", "napansin", "nasilayan"],
  "showed": ["ipinakita", "nilahad", "inilantad", "isinawalat", "prinisent"],
  "member": ["kasapi", "miyembro", "tauhan", "kabilang", "myembro"],
  "american": ["amerikano", "dayuhan", "kano", "mamamayan"],
  "product": ["produkto", "paninda", "gawa", "resulta", "prodak"],
  "editor": ["editor", "tagasuri", "patnugot", "manunulat"],
  "critical": ["kritikal", "mabusisi", "mapanuri", "delikado"],
  "tourism": ["tourism", "turismo", "paglalakbay", "bakasyon", "turism"],
  "religion": ["relihiyon", "paniniwala", "pananampalataya", "sekta", "relidyon", "religion"],
  "performance": ["pagtatanghal", "palabas", "programa", "dula", "perpo"],
  "exactly": ["mismong", "sadya", "eksakto", "tumpak"],
  "test": ["test", "pagsubok", "pagsusulit", "eksamen"],
  "effective": ["epektibong", "mabisa", "malakas", "maganda", "epektib", "epektibo"],
  "case": ["kaso", "usapin", "asunto", "problema", "keys"],
  "among": ["among", "gitna", "kabilang", "sa", "amung"],
  "assessment": ["pagtataya", "pagsusuri", "pagtimbang", "paghula", "pag-e-evaluate"],
  "challenges": ["challenges", "hamon", "pagsubok", "problema", "tsalenges"],
  "website": ["website", "pahina", "portal", "site", "websayt"],
  "congregation": ["kongregasyon", "samahan", "kapulungan", "grupo"],
  "look": ["tingnan", "sulyapan", "masdan", "suriin", "tignan"],
  "covid": ["covid", "sakit", "pandemya", "virus", "kobid"],
  "cebu": ["cebu", "probinsya", "rehiyon", "sebu"],
  "carton": ["karton", "kahon", "papel", "lalagyan"],
  "spanish": ["espanyol", "kastila", "dayuhan", "wika"],
  "center": ["sentro", "center", "gitna", "puso", "pokus", "senter", "tanggapan"],
  "instead": ["halip", "kapalit", "imbes", "bagkus"],
  "success": ["tagumpay", "panalo", "wagi", "panaguri", "sakses"],
  "curricular": ["pangkurikulum", "pang-aralin", "pampaaralan", "pang-akademya", "kurikular"],
  "needing": ["nangangailangan", "humihingi", "kailangan", "umaasa", "nidi"],
  "august": ["august", "agosto", "buwan", "otso", "ogost"],
  "xiii": ["xiii", "labintatlo", "trese", "numero"],
  "changes": ["pagbabagong", "pag-iiba", "paglipat", "pagsasaayos", "tseng"],
  "feeling": ["damdamin", "emosyon", "puso", "nararamdaman", "pilings"],
  "next": ["susunod", "tatangkilik", "papasa", "kasunod", "nekst"],
  "inspiration": ["inspirasyon", "idolo", "lakas", "motibasyon", "inspi"],
  "stakeholders": ["stakeholders", "kasama", "kasosyo", "kasali", "istykeyholders"],
  "answer": ["sagot", "tugon", "solusyon", "reaksyon", "anser"],
  "every": ["tuwing", "kailanman", "kapag", "kada", "eberi"],
  "existing": ["umiiral", "nangyayari", "lumilitaw", "nagaganap", "nag-eexist"],
  "excellent": ["mahusay", "magaling", "matalino", "bihasa", "ekselent"],
  "eastern": ["silangang", "asya", "oryental", "silangan", "istern"],
  "license": ["license", "lisensya", "permiso", "pahintulot", "laysens"],
  "swf": ["swf", "pormat", "file"],
  "commission": ["commission", "komisyon", "lupon", "komite"],
  "excellence": ["kahusayan", "galing", "talento", "dunong", "yekspertis"],
  "facebook": ["facebook", "social", "media", "platform", "peysbuk"],
  "expression": ["pagpapahayag", "pagsasabi", "pagpapakita", "paglalahad", "pag-ekspress"],
  "element": ["elemento", "sangkap", "bahagi", "pwersa"],
  "repository": ["repository", "lalagyan", "taguan", "imbakan", "repositoryo", "animorepository", "repositori"],
  "obstacle": ["hadlang", "balakid", "harang", "sagabal", "bara", "obstakel"],
  "identify": ["matukoy", "malaman", "mahanap", "makita", "ma-identify"],
  "five": ["limang", "singko", "lima", "pang-lima", "payb"],
  "planning": ["planning", "pagpaplano", "pag-iisip", "paghahanda", "pluning"],
  "struggling": ["nahihirapan", "nagdurusa", "napapagod", "nalilito", "istruggling"],
  "maybe": ["marahil", "baka", "siguro", "posibleng", "meybi"],
  "technology": ["technology", "teknolohiya", "makinarya", "agham", "tek"],
  "absence": ["kawalan", "kakulangan", "pagkawala", "wala", "abis"],
  "seeing": ["nakikita", "napapansin", "napanonood", "nasisilayan", "sining"],
  "evangelization": ["ebanghelisasyon", "pangangaral", "misyon", "pagtuturo", "ebanghelyo"],
  "reader": ["mambabasa", "tagabasa", "manonood", "nakikinig", "rider"],
  "saints": ["santos", "banal", "santo", "apelyido"],
  "arrival": ["pagdating", "paglapit", "pag-uwi", "araybal"],
  "lopez": ["lopez", "pangalan", "apelyido", "lopes"],
  "age": ["edad", "taon", "gulang", "tanda", "edj"],
  "aiming": ["naglalayong", "nagpaplano", "nagnanais", "nag-aasam", "eyming"],
  "maria": ["maria", "babae", "birhen"],
  "script": ["baybayin", "sulat", "dalampasigan", "alpabeto"],
  "difficult": ["mahirap", "dukha", "komplikado", "mabigat", "hard"],
  "contribution": ["ambag", "kontribusyon", "tulong", "bigay"],
  "methodology": ["metodolohiya", "proseso", "sistema", "paraan", "metodolodyi"],
  "marcos": ["marcos", "pangalan", "apelyido", "markos"],
  "late": ["huli", "dulo", "wakas", "pinal", "leyt"],
  "necessary": ["kinakailangang", "kailangan", "dapat", "nararapat", "nided"],
  "arguably": ["masasabing", "matatawag", "maituturing", "maipapalagay", "seyings"],
  "asian": ["asian", "asyano", "oriental", "taga-asya", "asyan"],
  "asynchronous": ["asynchronous", "di-kasabay", "hiwalay", "sarili", "asinkronus"],
  "gig": ["gig", "trabaho", "palabas", "tugtog"],
  "global": ["global", "pandaigdig", "mundo", "pangkalahatan"],
  "doing": ["ginagawa", "binubuo", "tinatrabaho", "sinasagawa", "duing"],
  "motivation": ["motibasyon", "dahilan", "inspirasyon", "layunin"],
  "writer": ["manunulat", "awtor", "makata", "tagasulat", "rayter"],
  "percentage": ["bahagdan", "porsyento", "parte", "hati"],
  "freedom": ["kalayaan", "kasarinlan", "laya", "independensya", "pridem"],
  "graduate": ["graduate", "tapos", "nagtapos", "alumni", "gradweyt"],
  "recommendation": ["rekomendasyon", "mungkahi", "payo", "suhestiyon"],
  "spirit": ["diwa", "isip", "kaluluwa", "kahulugan", "isspiritu"],
  "higher": ["higher", "mataas", "lalo", "higit", "hayer"],
  "coast": ["coast", "baybayin", "pampang", "dalampasigan", "kowst"],
  "service": ["serbisyo", "lingcod", "tulong", "gawain"],
  "business": ["business", "negosyo", "kalakalan", "trabaho", "bisnes"],
  "home": ["tahanan", "bahay", "tirahan", "pamilya", "hom"],
  "bulacan": ["bulacan", "lalawigan", "probinsya", "bulakan"],
  "laguna": ["laguna", "probinsya", "lawa"],
  "junyee": ["junyee", "pangalan", "tao"],
  "foreign": ["banyagang", "dayuhan", "estranghero", "iba", "poren"],
  "character": ["tauhan", "tao", "empleyado", "karakter", "istap"],
  "html": ["html", "code", "wika", "web", "eys-ti-em-el"],
  "legend": ["alamat", "kwento", "mitolohiya", "pinagmulan", "lejend"],
  "increasingly": ["lalong", "higit", "mas", "labis", "mor"],
  "summary": ["buod", "kabuuan", "summary", "iksi", "samari"],
  "pre-service": ["pre-service", "bago", "nag-aaral", "pagsasanay", "pre-serbis"],
  "inquirer": ["inquirer", "nagtatanong", "pahayagan", "dyaryo", "inkuwayrer"],
  "his/hers": ["kanya", "kaniya", "sarili", "niya", "his/her"],
  "carried/brought": ["dala", "bitbit", "karga", "bunga"],
  "duty": ["tungkulin", "responsibilidad", "papel", "trabaho", "dyuti"],
  "scope": ["saklaw", "sakop", "abot", "limitasyon", "iskop"],
  "name": ["pangalan", "tawag", "ngalan", "titulo", "neym"],
  "formed": ["nabuo", "nagawa", "nayari", "natapos", "buo"],
  "famous": ["kilala", "sikat", "tanyag", "alam"],
  "zoom": ["zoom", "lapit", "video", "tawag", "zum"],
  "worldwide": ["pandaigdigang", "nasyonal", "global", "buong"],
  "elementary": ["elementarya", "mababa", "paaralan", "grado", "elementari"],
  "collective": ["kolektibong", "pangkalahatan", "samahan", "grupo", "kolektib"],
  "tugano": ["tugano", "apelyido", "tao", "pangalan"],
  "act": ["act", "batas", "gawa", "kilos", "akt"],
  "road": ["road", "kalsada", "daan", "kalye", "rod"],
  "emerged": ["lumabas", "nagpakita", "sumulpot", "nalaman", "apir"],
  "natural": ["likas", "natural", "katutubo", "orihinal", "karaniwan", "normal"],
  "video": ["video", "pelikula", "palabas", "clip", "bidyo"],
  "selection": ["pagpili", "pagkuha", "pagpapasya", "eleksyon", "pag-tsus"],
  "thorough": ["masusing", "maingat", "mabusisi", "matalim", "maigi"],
  "analyze": ["suriin", "tignan", "busisiin", "aralin", "i-analisa"],
  "megaworld": ["megaworld", "kumpanya", "negosyo", "korporasyon"],
  "site": ["site", "lugar", "pwesto", "website", "sayt"],
  "struggle": ["pakikibaka", "laban", "away", "giyera", "istragel"],
  "performing": ["isinasagawa", "ginagawa", "tinatrabaho", "pinapatupad", "duing"],
  "tool": ["kasangkapan", "gamit", "materyales", "instrumento", "tul"],
  "paragua": ["paragua", "palawan", "lugar", "probinsya"],
  "ensure": ["matiyak", "masiguro", "malaman", "mapatunayan", "isyur"],
  "march": ["march", "marso", "buwan", "petsa", "mats"],
  "mactan": ["mactan", "isla", "cebu"],
  "delivery": ["delivery", "padala", "bigay", "paghahatid", "diliberi"],
  "summit": ["summit", "pulong", "tuktok", "pagtitipon", "samit"],
  "agreeing": ["sumasang", "pumapayag", "umaayon", "bumuboto", "agri"],
  "written": ["isinulat", "ginawa", "inakda", "nilimbag", "royt", "pasulat", "nakasulat", "titik", "papel", "ritten"],
  "beautiful": ["magandang", "marikit", "mabuti", "maayos", "byutiful"],
  "sway": ["kemdeng", "sayaw", "kembot", "galaw"],
  "tourist": ["turista", "dayuhan", "bisita", "byahero", "turis"],
  "ched": ["ched", "komisyon"],
  "presented": ["inilahad", "pinakita", "binanggit", "inilabas", "prinesent"],
  "instruction": ["instruction", "utos", "turo", "panuto", "instraksyon"],
  "relevance": ["kinalaman", "kaugnayan", "koneksyon", "pakialam", "releyted"],
  "representation": ["representasyon", "simbolo", "imahe", "kinatawan"],
  "collaborative": ["kolaboratibong", "tulungan", "samahan", "grupo", "kolaboratib"],
  "give": ["magbigay", "magkaloob", "mag-abot", "mag-alay", "gib"],
  "moderately": ["moderately", "katamtaman", "medyo", "sakto", "modereytli"],
  "historical": ["historical", "makasaysayan", "nakaraan", "luma", "historikal"],
  "found": ["matatagpuan", "makikita", "hahanapin", "naroroon", "paund"],
  "action": ["pagkilos", "galaw", "aksyon", "gawa"],
  "successful": ["matagumpay", "wagi", "panalo", "nakaangat", "saksespul"],
  "start": ["simula", "umpisa", "una", "pinagmulan", "start"],
  "john": ["john", "juan", "pangalan", "tao", "dyon"],
  "particles": ["ay", "ang", "mga", "si", "sina", "nina", "kay", "sa", "na", "ng", "at", "ni"],
  "conducted": ["isinagawang", "ginawa", "tinapos", "nilikha", "kondukted"],
  "mix": ["mix", "combination", "kombinasyon", "halo", "halu-halo"],
  "influence": ["influence", "influences", "impluwensya", "impluwensiya", "impluwensiyang"],
  "colonization": ["colonization", "pananakop", "kolonisasyon"],
  "impact": ["impact", "epekto", "impluwensya", "impak"],
  "priority": ["priority", "prioridad", "pangunahin"],
  "strive": ["strive", "nagsisikap", "nagsisikap", "nagpupursigi"],
  "secure": ["secure", "makamit", "makuha", "matiyak"],
  "future": ["future", "kinabukasan", "hinaharap"],
  "combination": ["combination", "kombinasyon"]
}

# Define Categorization Logic
# Stopwords (Functional/Noise)
STOPWORDS_KEYS = {
    "particles",
    "this", "one", "not", "have", "so that", "as", "if", "their", "when", "for", "https", "do", "of this", "other", "from",
    "only", "because", "more", "yet", "when (past)", "com", "www", "can", "according to", "through", "became", "usage",
    "become", "org", "person", "his", "so", "here", "in", "part", "they", "to", "all", "based", "without", "like",
    "level", "doi", "where", "online", "but", "using", "each", "own", "he", "must", "about", "some", "lot", "until",
    "edu", "volume", "ateneo", "katipunan", "inside", "first", "like this", "being", "my", "index", "primary", "city",
    "i", "country", "effect", "paper", "task", "two", "perspective", "our", "what", "use", "visible", "table", "how", "example",
    "los", "issue", "of", "national", "essay", "creation", "review", "word", "type", "reyes", "new", "many", "included",
    "important", "connection", "related", "result", "while", "high", "inc", "self", "current", "process", "corner",
    "also", "even", "personal", "year", "value", "php", "thing", "time", "said", "indeed", "http", "none", "retrieved",
    "that", "towards", "challenge", "importance", "digital", "continuous", "quezon", "particular", "standard", "topic",
    "reason", "salle", "day", "mean", "awareness", "having", "work", "content", "big", "need", "following", "understanding",
    "field", "gives", "problem", "clear", "grade", "besides", "issn", "local", "meeting", "press", "whole", "characteristic",
    "three", "rizal", "lack", "mentioned", "completely", "airport", "orderly", "now", "making", "likewise", "form",
    "image", "giving", "lots", "enough", "his/her", "showing", "want", "mixed", "saleable", "addition", "response",
    "pdf", "tagalog", "wide", "gov", "chosen", "finish", "step", "ojs", "again", "other side", "under", "state", "after",
    "why", "execution", "factor", "four", "normal", "meanwhile", "true", "focused", "basic", "december", "diliman",
    "identity", "conducted", "performance", "disease", "we", "pasma", "second", "quality", "who", "had", "letter",
    "news", "any", "total", "dlsu", "then", "according", "emphasis", "positive", "published", "way", "individual",
    "juan", "cause", "impact", "accepted", "fellow", "often", "number", "june", "event", "th", "common", "its",
    "ancient", "message", "wvsu", "jstor", "picture", "possible", "refers", "interest", "stable", "significant",
    "materials", "group", "specific", "really", "model", "respondent", "unfolding", "ability", "both", "graduated",
    "reference", "complete", "exactly", "serving", "understand", "correct", "open", "although", "page", "discovered",
    "modern", "say", "majority", "attention", "required", "meaningful", "almost", "right", "physical", "stage",
    "print", "mine", "improving", "cross", "resurrection", "power", "sustainable", "youtube", "did", "active", "such",
    "former", "easy", "sake", "hall", "tracer", "know", "will use", "acceptance", "difference", "outside", "your",
    "general", "code", "against", "consisting", "senior", "core", "called", "solution", "seems", "last", "jose",
    "master", "scholar", "frequency", "situation", "analyzed", "support", "order", "considered", "saw", "showed",
    "member", "american", "product", "editor", "critical", "test", "effective", "case", "among", "assessment",
    "challenges", "used", "instead", "success", "needing", "august", "xiii", "changes", "feeling", "next",
    "inspiration", "stakeholders", "made", "answer", "every", "existing", "excellent", "license", "note",
    "commission", "excellence", "expression", "element", "repository", "obstacle", "identify", "five", "planning",
    "area", "struggling", "maybe", "view", "absence", "side", "seeing", "implementation", "reader", "sometimes",
    "arrival", "lopez", "age", "aiming", "maria", "sector", "script", "difficult", "contribution", "methodology",
    "marcos", "late", "necessary", "arguably", "asian", "asynchronous", "gig", "global", "doing", "motivation",
    "writer", "percentage", "freedom", "graduate", "gave", "recommendation", "spirit", "rights", "the", "higher",
    "coast", "service", "business", "home", "bulacan", "laguna", "junyee", "foreign", "character", "html", "legend",
    "forming", "negative", "increasingly", "summary", "pre-service", "inquirer", "his/hers", "carried/brought", "duty",
    "scope", "name", "formed", "of/from", "to/with", "famous", "zoom", "worldwide", "elementary", "discussion",
    "policy", "collective", "tugano", "act", "road", "emerged", "natural", "video", "selection", "thorough",
    "description", "instrument", "movement", "analyze", "megaworld", "site", "struggle", "performing", "iii", "tool",
    "paragua", "ensure", "march", "delivery", "summit", "agreeing", "written", "beautiful", "sway", "tourist", "ched",
    "presented", "instruction", "relevance", "associated", "representation", "maintain", "pro", "questionnaire",
    "collaborative", "perception", "enrique", "expert", "beliefs", "give", "believes", "popular", "except", "may",
    "low", "near", "happening", "there", "moderately", "care", "helpful", "found", "action", "successful", "start",
    "john", "score"
}

# Separate data
dictionary_data = {}
stopwords_data = {}

for key, value in all_data.items():
    if key in STOPWORDS_KEYS:
        stopwords_data[key] = value
    else:
        dictionary_data[key] = value

# Save to files
with open("/Users/user/Documents/3rd year/2nd sem/rabin-karp-algorithm/dictionary.json", "w", encoding="utf-8") as f:
    json.dump(dictionary_data, f, indent=2, ensure_ascii=False)

with open("/Users/user/Documents/3rd year/2nd sem/rabin-karp-algorithm/stopwords.json", "w", encoding="utf-8") as f:
    json.dump(stopwords_data, f, indent=2, ensure_ascii=False)

print("Files updated successfully.")
